name: SKL_Portal_Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.9'}
      - name: Install
        run: pip install requests
      - name: Run
        env: {MAPS_API_KEY: "${{ secrets.MAPS_API_KEY }}"}
        run: python build_sheets.py
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
